#!/usr/bin/env bash
# installs nginx and listens at port 80

sudo apt -y update
sudo apt -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
# sudo systemctl start nginx
