#!/usr/bin/env bash
# installs nginx and listens at port 80

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo systemctl start nginx
