#!/usr/bin/env bash
# custom 404 response handler page

# backup and inits erroe files name
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
error_file="error_404.html"

# sets up nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# creates custom 404 page
sudo touch "/var/www/html/$error_file"
echo "Ceci n'est pas une page" | sudo tee "/var/www/html/$error_file"

# makes 404 error request retieve said page
NEW_STRING1="\\\terror_page 404 /$error_file;\n\tlocation = /$error_file {\n\t\troot /var/www/html;\n\t\tinternal; \n\t}\n"
NEW_STRING2="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \n\t}\n"

sudo sed -i "42i $NEW_STRING2" /etc/nginx/sites-available/default
sudo sed -i "45i $NEW_STRING1" /etc/nginx/sites-available/default

sudo servicectl restart nginx
