#!/usr/bin/env bash
# edits the haproxy config

# sets up nginx and haproxy
# but stops nginx to prvent port conflict
# while accessing port 80
sudo apt-get update
sudo apt-get install nginx && sudo service nginx stop

# sets up haproxy
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get install -y haproxy=2.7.\*

# backup
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# edits comfig
CONFIG1="\\\nfrontend http\n\tmode http\n\tbind *:80\n\tdefault_backend server"
CONFIG2="\\\nbackend server\n\tmode http\n\tbalance roundrobin\n\tserver 141974-web-01 54.198.80.112:80\n\tserver 141974-web-02 18.209.178.238:80\n"

# adds edit to config
sudo sed -i "\$a $CONFIG1" /etc/haproxy/haproxy.cfg
sudo sed -i "\$a $CONFIG2" /etc/haproxy/haproxy.cfg

# configures haproxy to use an init script
sudo sed -i "\$a ENABLED=1" /etc/default/haproxy
sudo service haproxy start
