#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# but 9th iteration prints "hi" after best School
count=0
while [ $count -ne 10 ]; do
	echo "Best School"
	if [ $count -eq 8 ] 
	then
		echo "Hi"
	fi
	(( count += 1 ))
done
