#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20
# with superstitious edits
count=1
while [ $count -ne 21 ]; do
	echo "$count"
	case $count in
	4)
		echo "bad luck from China";;
	9)
		echo "bad luck from Japan";;
	17)
		echo "bad luck from Italy";;
	esac
	(( count += 1 ))
done
