#!/usr/bin/env bash
# changes /etc/hosts
# (To be run in Docker container; else revert hostfile back)
# https://web.archive.org/web/20171117023601/http://blog.jonathanargentiero.com/docker-sed-cannot-rename-etcsedl8ysxl-device-or-resource-busy/

cp /etc/hosts copy_host
sed -i s/127.0.0.1/127.0.0.2\\tlocalhost\\n8.8.8.8\\tfacebook.com/g copy_host
cp -f copy_host /etc/hosts
