#!/usr/bin/env bash
# bash script listens to port 98 of localhost
# Run: (terminal 0): sudo ./[filename]
# Run: (terminal 1): telnet localhost 98
# See: (terminal 1): Trying 127.0.0.2... ; Connected to localhost.
# Type (terminal 1): Hey there!
# See: (terminal 0): Hey there!

nc -l 98
